# vim: expandtab tabstop=2 shiftwidth=2
name: IPA Down

env:
  PYTHONIOENCODING: utf-8
  APP_BUNDLE_ID: com.roblox.robloxmobile
  
# Allow Release
permissions: write-all

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  download_ipa:
    name: 'IPATool Operations'
    runs-on: "windows-latest"
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2

      - name: Setup ipatool-py
        run: |
          git clone -b itunes_server https://github.com/Yakov5776/ipatool-py
          pip3 install -r ipatool-py/requirements.txt
          mkdir -p ipaDown
        shell: bash

      - name: Setup iTunes Header Service
        uses: NyaMisty/actions-iTunes-header@master
        with:
          apple_id: ${{ secrets.APPLE_ID }}
          apple_id_pwd: ${{ secrets.APPLE_ID_PWD }}
        
      - name: Execute operation
        id: operation
        run: |
            output=$(python3 ipatool-py/main.py --json lookup -b $APP_BUNDLE_ID -c US \
                                                download -o ipaDown -s http://127.0.0.1:9000 )

            echo "Got Downloading JSON result: $output"
            echo "NEED_IPA_RELEASE=1" >> $GITHUB_ENV
            echo "APP_NAME=$(echo "$output" | jq -r '.appName')" >> $GITHUB_ENV
            echo "APP_BUNDLE_ID=$(echo "$output" | jq -r '.appBundleId')" >> $GITHUB_ENV
            echo "APP_VER=$(echo "$output" | jq -r '.appVer')" >> $GITHUB_ENV
            echo "APP_ID=$(echo "$output" | jq -r '.appId')" >> $GITHUB_ENV
            echo "APP_VER_ID=$(echo "$output" | jq -r '.appVerId')" >> $GITHUB_ENV
            echo "DOWNLOAD_URL=$(echo "$output" | jq -r '.downloadUrl')" >> $GITHUB_ENV
        shell: bash
        
      - name: Check if release exists
        run: |
          $response = Invoke-RestMethod -Method Get -Uri "https://api.github.com/repos/Yakov5776/roblox-action-ipadown/releases/tags/${{ env.APP_BUNDLE_ID }}-${{ env.APP_ID }}-${{ env.APP_VER_ID }}"
          $id = $response.id
          if ($null -eq $id) { $id = "null" }
          echo "EXISTING_RELEASE=$id" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh
        
      - name: "Upload package"
        uses: NyaMisty/upload-artifact-as-is@master
        if: env.EXISTING_RELEASE == 'null'
        with:
          path: ipaDown\*
      
      - name: Pushing to release
        uses: ncipollo/release-action@v1
        if: env.EXISTING_RELEASE == 'null'
        with:
          name: "IPADown: ${{ env.APP_NAME }} - ${{ env.APP_VER }}"
          body: >-
            ${{ format(fromJSON('"appName: {0}\nappBundleId: {1}\nappVer: {2}\nappId: {3}\nappVerId: {4}\n"'), 
                  env.APP_NAME, 
                  env.APP_BUNDLE_ID, 
                  env.APP_VER, 
                  env.APP_ID, 
                  env.APP_VER_ID
                ) }}
          commit: ${{ github.sha }}
          tag: "${{ env.APP_BUNDLE_ID }}-${{ env.APP_ID }}-${{ env.APP_VER_ID }}"
          artifacts: ipaDown\*

          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: false
